# Canal de entrada (Kafka -> Consumer). O broker fica interno no cluster pelo
# Service bootstrap criado pelo AMQ Streams.
kafka.bootstrap.servers=orders-kafka-kafka-bootstrap:9092
mp.messaging.incoming.orders-in.connector=smallrye-kafka
mp.messaging.incoming.orders-in.topic=orders
mp.messaging.incoming.orders-in.group.id=order-consumer
mp.messaging.incoming.orders-in.auto.offset.reset=earliest
mp.messaging.incoming.orders-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
